function toppart()
dev.colorwrite("* * * * * * * * *","white","blue")
dev.colorprint("             !!Murica!!               ","blue","red")
dev.colorwrite(" * * * * * * * * ","white","blue")
dev.colorprint("             Fuck yeah               ","red","white")
end
function bottompart()
dev.colorprint("                                                     ","red","red")
dev.colorprint("                                                     ","white","white")
end
toppart()
toppart()
toppart()
toppart()
bottompart()
bottompart()
bottompart()
bottompart()
dev.colorwrite("                                                     ","white","red")
dev.colorprint(" ","white","black")
